config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bikes do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create, :index]
  end
  resources :bookings, only: [:show, :index, :edit, :update, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :daily_rate, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :category, inclusion: { in: ['Road Bike', 'Mountain Bike', 'Commuter Bike'] }
end
# belongs_to :category

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bike
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bike

  validates :content, presence: true, length: { in: 4..300 }
  validates :rating, presence: true, inclusion: { in: 1..5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bikes
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :bio])
  end

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /bikes
  def index
    params[:query].present? ? @bikes = Bike.where("address ILIKE ?", "%#{params[:query]}%") : @bikes = Bike.all
    @markers = @bikes.geocoded.map do |bike|
      {
         lat: bike.latitude,
         lng: bike.longitude,
         info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
         image_url: helpers.asset_url("tyre.png")
      }
    end
  end

  # GET bikes/:id
  def show
    @bike = Bike.find(params[:id])
    @booking = Booking.new
    @bookings = @bike.bookings
    @users_booked = @bookings.map {|booking| booking.user}
    @review = Review.new
    @markers =
      [{
        lat: @bike.latitude,
        lng: @bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bike: @bike }),
        image_url: helpers.asset_url("tyre.png")
      }]
  end

  # GET /bikes/new
  def new
    @bike = Bike.new

  end

  # GET /bikes/:id/edit
  def edit
  end

  # POST /bikes
  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    # authorize @bike
    if @bike.save
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  #PATCH/PUT /bikes/:id
  def update
    if @bike.update(bike_params)
      redirect_to @bike, notice: "Listing was updated!"
    else
      render :edit
    end
  end

  # DELETE /bikes/:id
  def destroy
    @bike.destroy
    redirect_to bikes_url, notice: "Bike was removed!"
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
    authorize @bike
  end

  def bike_params
    params.require(:bike).permit(:name, :description, :daily_rate, :address, :photo, :category)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :find_bike, only: [:new, :create]

  def index
    @bookings = Booking.all
  end

  def show
    # calling set_booking
    @bike = @booking.bike
  end

  def new
    @booking = Booking.new
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    @booking.user = @user
    total_price_calc

    if current_user == @bike.user
      flash[:alert] = "Cannot book your own bike!"
      render :new
    elsif @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit
    # calling set_booking
    @bike = @booking.bike
  end

  def update
    # calling set_booking
    @bike = @booking.bike
    total_price_calc
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    # calling set_booking
    @booking.destroy
    redirect_to bookings_path
  end



  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def find_bike
    @bike = Bike.find(params[:bike_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :bike_id)
  end

  def total_price_calc
    start_date = Date.parse(booking_params[:start_date])
    end_date = Date.parse(booking_params[:end_date])
    total_days = (end_date - start_date).to_i + 1
    total_price = total_days * @bike.daily_rate
    @booking.total = total_price
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_bike, only: [:index, :new, :create]

  def index
    @reviews = Review.where(bike: @bike)
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.bike = @bike
    @review.user = current_user

    if @review.save
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_bike
    @bike = Bike.find(params[:bike_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # @name = current_user.name
    # @bikes = @user.bikes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_form.html.erb
<%= simple_form_for @bike do |f| %>
  <%= f.input :name , class: "simp-form-input"%>
  <%= f.input :description, class: "simp-form-input" %>
  <%= f.input :daily_rate, class: "simp-form-input" %>
  <%= f.input :category,
              collection: ['Road Bike', 'Mountain Bike', 'Commuter Bike'],
              class: "simp-form-input" %>
  <%= f.input :address,
              input_html: { data: { geocoder_target: "address" }, class: "d-none"},
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  <%= f.input :photo, as: :file , class: "simp-form-input"%>
  <%= f.submit "List Bike", class: "btn btn-form-go" %>
<% end %>

app/views/bikes/_info_window.html.erb
<div class="info-window">
  <h2><%= link_to bike.name, bike_path(bike) %></h2>
  <p><%= bike.address %></p>
  <p><%= bike.description %></p>
</div>

app/views/bikes/edit.html.erb
<div class="form-container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>Edit your bike: <%= @bike.name  %></h1>
      <%= render 'form', bike: @bike %>
      <%= link_to 'Cancel', bike_path(@bike), class: "btn-form-cancel" %>
    </div>
  </div>
</div>

app/views/bikes/index.html.erb
<%# <div class="main"> %>
<div class="index-container">
  <div class="all-cards">
  <div class="title-container">
  <%= form_tag bikes_path, method: :get do %>
  <div style="margin: 0 auto;" class="search-form-control form-group">
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Type a location" %>
    <%= submit_tag "Search", class: "btn btn-ghost" %>
  </div>
  <% end %>
</div>
  <div class="cards-container">
    <% @bikes.each do |bike| %>
      <div class="bike-card">
        <% if bike.photo.key? %>
          <%= link_to bike_path(bike) do %>
            <%= cl_image_tag(bike.photo.key) %>
          <% end %>
        <% else %>
          <%= link_to bike_path(bike) do %>
            <%= cl_image_tag('28-287336_welcome-road-bike-vector_ywbbgd') %>
          <% end %>
        <% end %>
            <div class="bike-card-infos">
              <div>
                <h2><%= link_to bike.name, bike_path(bike) %> - £<%= bike.daily_rate %>0/day</h2>
                <p><%= bike.address.split(",")[1] %></p>
              </div>
            <%# <h2 class="bike-card-pricing">£<%= bike.daily_rate %>
            </div>
          </div>
    <% end %>
  </div>
  </div>
  <div id="map" class=""
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
<%# </div> %>

app/views/bikes/new.html.erb
<div class="form-container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>List your Bike</h1>
      <%= render 'form', bike: @bike %>
      <%= link_to "Cancel", bikes_path, class: "btn-form-cancel" %>
    </div>
  </div>
</div>

app/views/bikes/show.html.erb
<div class="bike-show-container">
  <div class="row">

    <div class="col-8">
      <div class="show-card-img" style="background-image: url('<%= cl_image_path @bike.photo.key %>')">
      </div>
      <div class="show-description">
        <h2>About this bike</h2>
        <p><%= @bike.description %></p>
      </div>
      <div class="show-location">
        <h2>Bike Location</h2>
        <p><%= @bike.address %></p>
        <div style="width: auto; height: 500px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
      <div class="show-reviews">
        <% if @users_booked.include?(current_user) %>
          <h2>Leave a Review</h2>
          <%= simple_form_for [@bike, @review] do |f| %>
            <%= f.input :content %>
            <%= f.input :rating, collection: 1..5 %>
            <%= f.submit "Submit Review", class:"btn-form-go"%>
          <% end %>
        <% end %>

        <h2>Past Reviews</h2>
        <div class="reviews-container">
          <% @bike.reviews.each do |review| %>
            <div class="review-card">
              <div class="review-content">
                <img src="https://res.cloudinary.com/daunt2sk5/image/upload/v1652816262/avatar_istock_yhmpzg.jpg" class= "avatar">
                <div class="review-card-info">
                  <h3><%= review.user.name %></h3>
                  <p><%= review.content %></p>
                </div>
              </div>
              <p><%= review.created_at %></p>
              <div class="star-div">
                <% review.rating.to_i.times do %>
                  <p>⭐️</p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-4">
      <h1><%= @bike.name %></h1>
      <div class="show-card-booking">
        <h3>Bike Owner: <%= @bike.user.name %></h3>
        <div class="show-card-pricing">
          <div class="pricing-box">
            <p><strong>Daily</strong></p>
            <p>£<%= @bike.daily_rate %>/day</p>
          </div>
          <div class="pricing-box">
            <p><strong>7+ days</strong></p>
            <p>£<%= @bike.daily_rate * 0.8 %>/day</p>
          </div>
          <div class="pricing-box">
            <p><strong>30+ days</strong></p>
            <p>£<%= @bike.daily_rate * 0.6 %>/day</p>
          </div>
        </div>
        <%= simple_form_for [@bike, @booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true, class: "simp-form-input" %>
          <%= f.input :end_date, as: :date, html5: true, class: "simp-form-input" %>
          <%= f.submit "Book this Bike", class: "btn btn-form-go"%>
        <% end %>
      </div>
      <div class="btn-container">
        <% if @bike.user == current_user %>
            <%= link_to "Edit this listing", edit_bike_path(@bike), class: "edit-btn" %>
            <%= link_to "Remove this listing",
              bike_path(@bike),
              method: :delete,
              data: {confirm: "Are you sure?"}, style: "red bold", class: "delete-btn" %>
        <% end %>
      </div>
    </div>
    <%= link_to "Back to bikes", bikes_path, class: "btn-back" %>
  </div>
</div>


<%# <div style="url(https://res.cloudinary.com/dx4u8lsnu/image/upload/v1652528893/Screenshot_2022-05-14_at_12.46.37_hrj2tj.png)"></div>
<div style="url(https://res.cloudinary.com/dx4u8lsnu/image/upload/v1652022260/tobias-cornille-ZPpC98Vus3k-unsplash_xpegsv.jpg)"></div> %>

app/views/bookings/_form.html.erb
<%= simple_form_for [@bike, @booking] do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.submit "Rent Bike"%>
<% end %>

app/views/bookings/edit.html.erb
<div class="form-container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>Edit rental of<% @booking.bike %></h1>
      <%= simple_form_for @booking do |f| %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= f.submit "Confirm changes", class: "btn btn-form-go" %>
      <% end %>
      <%= link_to "Cancel", bookings_path, class: "btn-form-cancel"  %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="booking-title">
  <h1>All Bookings</h1>
</div>
<div class="bookings-container">
    <% @bookings.each do |booking| %>
      <div class="booking-card">
        <div class="booking-card-info">
          <h2>Booking <%= booking.id %></h2>
          <p>Bike:       <%= booking.bike.name %></p>
          <p>Booked by:  <%= booking.user.name %></p>
          <p>Dates:      <%= booking.start_date %> - <%= booking.end_date %></p>
          <p>Total Fee:  £<%= booking.total %></p>
          <% if booking.user == current_user %>
            <% if Date.today < booking.end_date  %>
              <%= link_to "Edit", edit_booking_path(booking) %>
              <%= link_to "Cancel",
                booking_path(booking),
                method: :delete,
                data: {confirm: "Are you sure?"}, style: "red bold" %>
            <% else %>
              <%= link_to "Leave Review", bike_path(booking.bike) %>
            <% end %>
          <% end %>
        </div>
        <img src="<%= cl_image_path booking.bike.photo.key %>" class="booking-img">
      </div>
   <% end %>
</div>
   <%= link_to bikes_path do %>
    <div class="btn-back">Back to Bikes</div>
   <% end %>

app/views/bookings/new.html.erb
<div class="form-container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>Your rental of<% @booking.bike %></h1>
      <%= render 'form', booking: @booking %>
      <%= link_to "Cancel", bikes_path %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Booking #<%= @booking.id %></h1>

<h3><%= @booking.bike.name %></h3>
<p><%= @booking.start_date %></p>
<p><%= @booking.end_date %></p>
<p><%= @booking.total %></p>

<%= link to "Edit Booking", edit_bike_booking_path(@booking) %>
<%= link_to "Delete Booking",
  booking_path(@booking),
  method: :delete,
  data: {confirm: "Are you sure?"}, style: "red bold" %>
<%= link_to "Back to bikes", bikes_path, class: "btn-back" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CyclonRentals</title>
    <%= favicon_link_tag asset_path('logo_black_c_only.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>

</html>

app/views/pages/_info_window.html.erb
<div class="info-window">
<h2><%= link_to bike.name, bike_path(bike) %></h2>
<p><%= bike.address %></p>
<p><%= bike.description %></p>
</div>

app/views/pages/bike_animation.html.erb
<div class="screen">
  <div class="bike-screen">
    <div class="bike">
      <div class="left-handle"></div>
      <div class="left-handle-brake"></div>
      <div class="right-handle"></div>
      <div class="right-handle-brake"></div>
      <div class="headlight"></div>
      <div class="left-pedal"></div>
      <div class="left-pedal-rod"></div>
      <div class="left-pedal-footer"></div>
      <div class="left-suspension"></div>
      <div class="right-pedal"></div>
      <div class="right-pedal-rod"></div>
      <div class="right-pedal-footer"></div>
       <div class="right-suspension"></div>
      <div class="body"></div>
      <div class="body-rod"></div>

      <div class="wheel"></div>
      <div class="seat"></div>
    </div>
  </div>
  <div class="road"></div>
</div>

app/views/pages/bikeanimation.html.erb
<div class="screen">
  <div class="bike-screen">
    <div class="bike">
      <div class="left-handle"></div>
      <div class="left-handle-brake"></div>
      <div class="right-handle"></div>
      <div class="right-handle-brake"></div>
      <div class="headlight"></div>
      <div class="left-pedal"></div>
      <div class="left-pedal-rod"></div>
      <div class="left-pedal-footer"></div>
      <div class="left-suspension"></div>
      <div class="right-pedal"></div>
      <div class="right-pedal-rod"></div>
      <div class="right-pedal-footer"></div>
       <div class="right-suspension"></div>
      <div class="body"></div>
      <div class="body-rod"></div>

      <div class="wheel"></div>
      <div class="seat"></div>
    </div>
  </div>
  <div class="road"></div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dx4u8lsnu/image/upload/v1651937961/cover_i5bypv.jpg);">
  <div class="container-home">
    <div> <img src="https://res.cloudinary.com/dx4u8lsnu/image/upload/v1652038169/CyclOn_Rentals_White_1.0_m7xxgw.png" width="500px" alt=""></div><br>
    <h1>Rent great</h1>
    <span class="typed-js" data-controller="typed-js"></span>
    <%# <div style="height: 50px;"><h1 class="typed-js" data-controller="typed-js"></h1></div> %>
     <%# <class="typed-js" data-controller="typed-js"> %>
    <h1>from people near you</h1>
      <%= form_tag bikes_path, method: :get do %>
        <div class="search-form-control form-group">
            <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Type a location" %>
            <%= submit_tag "Search", class: "btn btn-ghost" %>
        </div>
      <% end %>
  </div>
</div>
<br>

<br>
<h1 style="text-align: center;">Bike Categories</h1>
<br>
<div class="home-cards">
  <%= link_to bikes_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dx4u8lsnu/image/upload/v1652022260/tobias-cornille-ZPpC98Vus3k-unsplash_xpegsv.jpg)">
        Road Bikes
      </div>
  <% end %>

  <%= link_to bikes_path do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dx4u8lsnu/image/upload/v1652022260/coen-van-de-broek-On4QWhHJCEM-unsplash_b2niot.jpg)">
      Mountain Bikes
    </div>
  <% end %>

  <%= link_to bikes_path do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dx4u8lsnu/image/upload/v1652022260/dmitrii-vaccinium-9qsK2QHidmg-unsplash_dr93nj.jpg)">
      Commuter Bikes
    </div>
  </div>
<% end %>
<br>

<%# <div class="bike-animation"> %>
  <%# <div class="anim-screen">
  <div class="anim-bike-screen">
    <div class="anim-bike">
      <div class="left-handle"></div>
      <div class="left-handle-brake"></div>
      <div class="right-handle"></div>
      <div class="right-handle-brake"></div>
      <div class="headlight"></div>
      <div class="left-pedal"></div>
      <div class="left-pedal-rod"></div>
      <div class="left-pedal-footer"></div>
      <div class="left-suspension"></div>
      <div class="right-pedal"></div>
      <div class="right-pedal-rod"></div>
      <div class="right-pedal-footer"></div>
       <div class="right-suspension"></div>
      <div class="anim-body"></div>
      <div class="body-rod"></div>
      <div class="wheel"></div>
      <div class="seat"></div>
    </div>
  </div>
  <div class="road"></div>
</div> %>
<%# </div> %>

app/views/reviews/new.html.erb
<h1>Leave a Review:</h1>

<%= simple_form_for [@bike, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit Review"%>
<% end %>

<%= link_to "Cancel", bike_path(@bike) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer-expand-sm footer-light px-3 fixed-bottom">
  <div class="footer-word-links">
    <%= link_to "Sign up", bikes_path, class: "foot-link" %>
    <%= link_to "FAQ's", bikes_path, class: "foot-link" %>
    <%= link_to "Home", root_path, class: "foot-link" %>
    <p>Logged in as: <%= current_user ? current_user.name : "Not logged in" %></p>
  </div>
  <div class="footer-social-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    CyclOn Rentals <i class="fa-solid fa-bicycle"></i> Great bikes, ready to ride!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-cyclon px-3 fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <%= link_to root_path do %>
    <%= image_tag "logo_180px.png", alt: "logo", class: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active">
        <%= link_to "Book a bike", bikes_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item active">
      <%# <% if policy(Bike).create? %>
        <%= link_to "List your bike", new_bike_path, class: "nav-link" %>
      <%# <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to "Bookings", bookings_path, class: "nav-link" %>
      </li>
    </ul>
    <div class="nav-item dropdown">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar,  class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag "default_avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>

        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/">Home</a>
          <a class="dropdown-item" href="bikes">Book a Bike</a>
          <a class="dropdown-item" href="bikes/new">List your bike</a>
          <a class="dropdown-item" href="bookings">Bookings</a>
          <%= link_to "Account", current_user, class: "dropdown-item" %>
            <% if current_user %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
            <% end %>
            <% else %>
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
      <% end %>
      </div>
    </div>
  </div>
</div>